---
title: "STA DressCode - SQA Qualifications"
output: 
  html_document:
    toc: true
---
```{r global-options, include = FALSE}

knitr::opts_chunk$set(fig.dim = c(14, 7), out.width = '100%', out.height = '100%',
                      echo = FALSE, warning = FALSE, message = FALSE)
```

```{r}

library(tidyverse)
library(ggtext)

library(plotly)


# utilitiies & c.

dressCodeTheme <- theme_bw() +
                  theme(axis.text.y = element_markdown(size = 14),
                          axis.text.x = element_text(size = 12), #, angle = 45, vjust = 0.5),
                          axis.title.x = element_text(face = "bold", size = 16),
                          legend.title = element_blank(),
                          legend.text = element_text(size = 14),
                          plot.title = element_text(lineheight = 0.8, size = 20, face = "bold"),
                          text = element_text(family = "Helvetica")
                    )
                    
```

<h3>Top 5 Subjects over time by Gender &ndash; Highers</h3>
<p><br /></p>

```{r}

## top 5 subjects over time for Highers

sqa_top5s <- read_csv("data/sqa_top5s_highers.csv")

sqa_top5s <- sqa_top5s %>%

    distinct(year) %>%
    mutate(SubjectInTop5 = FALSE) %>%

    full_join(sqa_top5s %>%
              
                  distinct(Subject, Subject.label) %>%
                  mutate(SubjectInTop5 = FALSE)) %>%

    full_join(sqa_top5s %>%
              
                  distinct(gender) %>%
                  mutate(SubjectInTop5 = FALSE)) %>%


    left_join(sqa_top5s %>%
                  select(-c(popularity, popularityOverTime))) %>%
    mutate_at(vars(SubjectInTop5), ~ !is.na(NoOfStudents)) %>%

    left_join(sqa_top5s %>%
                  distinct(Subject, gender, popularity, popularityOverTime) %>%
                  arrange(desc(popularity), Subject, gender)) %>%

    select(-c(SubjectInTop5, popularity, popularityOverTime), everything(), SubjectInTop5, popularity, popularityOverTime) %>%
    mutate_at(vars(year), as.ordered) %>%
    mutate_at(vars(Subject, Subject.label, gender), as.factor) %>%
    mutate_at(vars(NoOfStudents, popularity), as.integer) %>%
  
    suppressMessages()

```

```{r}
# fig.cap = "blah"


plot1 <- sqa_top5s %>%
    highlight_key(~gender) %>%

    ggplot(aes(y = fct_reorder(Subject.label, popularity, na.rm = TRUE), x = popularityOverTime,
               text = paste(gender, " - choose", Subject, round(popularityOverTime * 100), "% of the time"),
               mode = "markers + text"
               )) +
        geom_segment(aes(xend = 0, yend = Subject.label), alpha = 0.45) +
        #geom_point(aes(colour = gender, shape = gender), size = 5) +
        #scale_shape_manual(values = c(-0x2640L, -0x2642L)) +
        scale_colour_manual(values = c("purple", "darkgreen")) +
        guides(size = FALSE, alpha = FALSE) +
        scale_x_continuous(labels = function(x) scales::percent(abs(x)), breaks = seq(0, 1, 0.2)) +
        ylab(NULL) + xlab("\nFrequency - in Top 5 Subjects Over Time (Excluding English & Maths)") +
        dressCodeTheme

plot1 +
  geom_point(aes(colour = gender, shape = gender), size = 5) +
  scale_shape_manual(values = c(-0x2640L, -0x2642L))        
              
```
<p><br /></p>

```{r}

plot1 <- plot1 + geom_point(aes(colour = gender, shape = gender), size = 2)


tickFont <- list(family = "Arial, sans-serif", size = 12)

ggplotly(plot1, tooltip = "text", dynamicTicks = "x", width = 1600, height = 600,
         margin = list(l = 0, r = 5, b = 5, t = 5, pad = 2),
         yaxis = yaxis <- list(automargin = FALSE, margin = list(l = 0, r = 5, b = 5, t = 5, pad = 2))) %>%

            style(hoveron = "points", hoverinfo = "text", hoverlabel = list(bgcolor = "white")) %>%
            layout(xaxis = list(tickformat = "%", tickfont = tickFont),
                   yaxis = list(tickfont = tickFont)) %>%
            highlight(on = "plotly_hover", off = "plotly_doubleclick", selected = attrs_selected(showlegend = FALSE)) #%>%
            #rangeslider()

#rm(plot1)
      
```
<p><br /></p>

```{r}

# fig.dim = c(14, 8)} - messing with theme

sqa_top5s %>%
    filter(SubjectInTop5) %>%
    
    ggplot(aes(y = fct_reorder(Subject.label, popularity, na.rm = TRUE), x = year,
               #text = paste(as.character(gender), " - choose", Subject, round(popularityOverTime * 100), "% of the time"), mode = "markers + text"
               )) +
        geom_point(aes(colour = gender, shape = gender), size = 5) +
        scale_shape_manual(values = c(-0x2640L, -0x2642L)) +
        scale_colour_manual(values = c("purple", "darkgreen")) +
        scale_x_discrete(breaks = seq(min(as.integer(levels(sqa_top5s$year))), max(as.integer(levels(sqa_top5s$year))), by = 2)) +
        guides(size = FALSE, alpha = FALSE) +
        ylab(NULL) + xlab("\nIn top 5 Subjects Over Time (Excluding English & Maths)") +
        dressCodeTheme +
        theme(axis.text.x = element_text(angle = 45, vjust = 0.5))
        
```
<p><br /></p>

```{r}

plot1 <- sqa_top5s %>%
    #filter(year == 2020) %>%
    #mutate_at(vars(popularity), ~ na_if(., !SubjectInTop5)) %>%

    ggplot(aes(y = fct_reorder(Subject.label, popularity, na.rm = TRUE), x = NoOfStudents,
               text = paste(as.character(gender), "- choose", Subject, round(popularityOverTime * 100), "% of the time, with",
                            NoOfStudents, "taking it in ", year),
               mode = "markers + text")) +
        geom_point(aes(colour = gender, shape = gender, size = popularityOverTime, frame = year, ids = Subject)) +
        scale_shape_manual(values = c(-0x2640L, -0x2642L)) +
        scale_colour_manual(values = c("purple", "darkgreen")) +
        guides(size = FALSE, alpha = FALSE) +
        expand_limits(x = 0) +
        ylab(NULL) + xlab("In top 5 Subjects Over Time (Excluding English & Maths)")  +
        dressCodeTheme +
        theme(axis.title.x = element_text(size = 14))

#plot1


tickFont <- list(family = "Arial, sans-serif", size = 12)

ggplotly(plot1, tooltip = "text", dynamicTicks = "x", width = 1800, height = 600,
         margin = list(l = 0, r = 5, b = 5, t = 5, pad = 2),
         yaxis = list(automargin = FALSE, margin = list(l = 0, r = 5, b = 5, t = 5, pad = 2))) %>%

            style(hoveron = "points", hoverinfo = "text", hoverlabel = list(bgcolor = "white")) %>%
            layout(xaxis = list(tickfont = tickFont, rangemode = "tozero"),
                   yaxis = list(tickfont = tickFont)) %>%
            highlight(on = "plotly_hover", off = "plotly_doubleclick", selected = attrs_selected(showlegend = FALSE))


rm(plot1)

```
